# Generated by Django 3.1 on 2020-08-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='id_calendario',
            new_name='id_ca',
        ),
    ]
