# Generated by Django 3.1 on 2020-08-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('departamento_id_depa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento')),
            ],
        ),
    ]
