# Generated by Django 3.1 on 2020-08-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calendario', '0001_initial'),
        ('Horario', '0001_initial'),
        ('Programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('calendario_id_calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.calendario')),
                ('horario_id_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.horario')),
                ('programa_id_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programa.programa')),
            ],
        ),
    ]
