# Generated by Django 3.1 on 2020-08-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='calendario_id_calendario',
        ),
    ]
