# Generated by Django 3.1 on 2020-08-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grado', '0003_auto_20200818_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grado',
            old_name='calendario_id_ca',
            new_name='ca_id_ca',
        ),
    ]
