# Generated by Django 3.1 on 2020-08-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grado', '0004_auto_20200818_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='ca_id_ca',
        ),
    ]
